on:
  pull_request:
  push:

jobs:
  # `nix build` runs `checkPhase` which runs unit and integration tests
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v10
    - uses: DeterminateSystems/magic-nix-cache-action@v4
    - name: Set up Rust cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: icwasm-${{ hashFiles('**/Cargo.lock') }}
    - run: |
        nix build .
