on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v10
    - uses: DeterminateSystems/magic-nix-cache-action@v4
    - name: Set up Rust cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: icwasm-${{ hashFiles('**/Cargo.lock') }}
    - run: |
        nix build .
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - run: |
        nix develop -c cargo test
   
